Icons are now placed in XDG compliant directory (~/.local/share/icons/hicolor) instead of ~/Applications/.icons. AppImages should now be themed correctly by Icon Themes.

diff --git a/fzam b/fzam
--- a/fzam
+++ b/fzam
@@ -9,8 +9,6 @@
 # The user is advised to check for viruses in every AppImage they download and only download from reputable sources and not from a random GitHub page.
 # The user may need to edit manually the .desktop file in case of any errors.
 
-#set -euo pipefail
-
 ## Variables
 FMENU="fzf --layout=reverse \
            --exact \
@@ -31,23 +29,25 @@ FMENU="fzf --layout=reverse \
 APPIMAGEDIR="$HOME/Applications/"
 
 # Directory where icons are placed
-APPIMAGEICONDIR="${APPIMAGEDIR}.icons/"
+APPIMAGEICONDIR="$HOME/.local/share/icons/hicolor"
 
 # Directory where desktop entries are placed in order for desktop environments to find them.
 # I recommend ~/.local/share/applications for a single user and /usr/local/share/applications for every user of the system.
 AMDESKTOPDIR="$HOME/.local/share/applications/" 
 verbose=0
 
-# Functions
+## Functions ##
+
+# Install / Integrate AppImage function.
 amintegrate() {
-    selection=$(find $HOME \( -path ${APPIMAGEDIR::-1} -o -path $HOME/.local/share/Trash -o -path $HOME/.cache \) -prune -o -type f -iname "*.AppImage" -print | ${FMENU} "Please type the location of the AppImage: ") 
+    selection=$(find "$HOME" \( -path "${APPIMAGEDIR::-1}" -o -path ~/.local/share/Trash -o -path ~/.cache \) -prune -o -type f -iname "*.AppImage" -print | ${FMENU} "Please type the location of the AppImage: ") 
     if [ -n "$selection" ]; then
 	## AppImage
 	
 	# Check if selection is an AppImage
 	amformat=$(file "${selection}" | awk -F ',' '{print $1}' | sed "s#${selection}: ##")
 	case $amformat in
-	    "ELF"*"LSB pie executable"|"ELF"*"LSB executable")
+	    "ELF"*"LSB"*"executable")
                 [[ "$verbose" -eq 1 ]] && echo "This file is an AppImage."
                 ;;
 	    *)
@@ -59,37 +59,40 @@ amintegrate() {
 	amname="$(basename "$selection" | tr 'A-Z' 'a-z' | awk -F '[_-]' '{print $1}' | sed 's#.AppImage##I')"
 	[[ "$verbose" -eq 1 ]] && echo "AppImage name is: ${amname}"
 	amlocation="${APPIMAGEDIR}${amname}.AppImage"
-	mv -i "${selection}" ${amlocation}
+	mv -i "${selection}" "${amlocation}"
 	
-	${amlocation} --appimage-extract > /dev/null || { echo "This is not a Type 2 AppImage"; exit 1; }
+	${amlocation} --appimage-extract > /dev/null || { echo "This AppImage cannot be extracted."; exit 1; }
 
 	## AppImage Icon
 	if [[ -n "$(readlink -f squashfs-root/.DirIcon)" ]]; then
 	    icon="$(readlink -f squashfs-root/.DirIcon)"
 	    [[ "$verbose" -eq 1 ]] && echo "Found icon as $icon"
 
-	    iconfmt="$(file ${icon} | awk '{print $2}' | tr 'A-Z' 'a-z')"
+	    iconfmt="$(file "${icon}" | awk '{print $2}' | tr 'A-Z' 'a-z')"
 	    [[ "$verbose" -eq 1 ]] && echo "Icon format is: $iconfmt"
-
-	    cp -i ${icon} ${APPIMAGEICONDIR}${amname}.${iconfmt} || echo "Could not copy icon file"
-	    [[ "$verbose" -eq 1 ]] && echo "Copied icon file to $HOME/Applications/.icons"
-    
-	    amicon="$(find ${APPIMAGEICONDIR} -type f -iname "*${amname}*")"
-	    
 	elif [[ -n $(find squashfs-root -maxdepth 1 -type f -iname "${amname}.*") ]]; then
 	    icon="$(find squashfs-root -maxdepth 1 -type f -iname "${amname}.*")"
 	    [[ "$verbose" -eq 1 ]] && echo "Found icon as $icon"
 
-	    iconfmt="$(file ${icon} | awk '{print $2}' | tr 'A-Z' 'a-z')"
-	    [[ "$verbose" -eq 1 ]] && echo "Icon format is: $iconfmt"
 
-	    cp -i ${icon} ${APPIMAGEICONDIR}${amname}.${iconfmt} || echo "Could not copy icon file"
-	    [[ "$verbose" -eq 1 ]] && echo "Copied icon file to $HOME/Applications/.icons"
-	    
-	    amicon="$(find ${APPIMAGEICONDIR} -type f -iname "*${amname}*")"
+	    iconfmt="$(file "${icon}" | awk '{print $2}' | tr 'A-Z' 'a-z')"
+	    [[ "$verbose" -eq 1 ]] && echo "Icon format is: $iconfmt"
 	else
 	    echo "Could not find icon."
-	    amicon="appimage"
+	    icon="appimage"
+	    iconfmt=""
+	fi
+	
+	# Move icon to XDG-compliant directory.
+	if [[ "$iconfmt" == "png" ]]; then
+	    iconsize="$(file ${icon} | awk '{print $5}')"
+	    [[ ! -d "$APPIMAGEICONDIR/${iconsize}x${iconsize}/apps" ]] && mkdir "${APPIMAGEICONDIR}/${iconsize}x${iconsize}/apps"
+	    cp -i "${icon}" "${APPIMAGEICONDIR}/${iconsize}x${iconsize}/apps/${amname}.${iconfmt}" || echo "Could not copy icon file."
+	    [[ "$verbose" -eq 1 ]] && echo "Copied icon file to ${APPIMAGEICONDIR}/${iconsize}x${iconsize}/apps"
+	elif [[ "$iconfmt" == "svg" ]]; then
+	    [[ ! -d "$APPIMAGEICONDIR/scalable/apps" ]] && mkdir "${APPIMAGEICONDIR}/scalable/apps"
+	    cp -i "${icon}" "${APPIMAGEICONDIR}/scalable/apps/${amname}.${iconfmt}" || echo "Could not copy icon file."
+	    [[ "$verbose" -eq 1 ]] && echo "Copied icon file to ${APPIMAGEICONDIR}/scalable/apps"
 	fi
 
 	## AppImage .desktop file
@@ -98,12 +101,12 @@ amintegrate() {
 	do
 	    [[ "$verbose" -eq 1 ]] && echo "Found .desktop file as $desktopfile"
 	    
-	    sed -i "/Exec/s#${amname}#${amlocation}#I" $desktopfile
-	    sed -i "/Exec/s#AppRun#${amlocation}#I" $desktopfile
-	    sed -i "/Icon/s#=.*#=${amicon}#I" $desktopfile
+	    sed -i "/Exec/s#${amname}#${amlocation}#I" "$desktopfile"
+	    sed -i "/Exec/s#AppRun#${amlocation}#I" "$desktopfile"
+	    sed -i "/Icon/s#=.*#=${amname}#I" "$desktopfile"
 	    [[ "$verbose" -eq 1 ]] && echo "All sed substitutions were done."
 	    
-	    cp -i "${desktopfile}" $AMDESKTOPDIR || echo "Could not copy .desktop file"
+	    cp -i "${desktopfile}" "$AMDESKTOPDIR" || echo "Could not copy .desktop file"
 	    [[ "$verbose" -eq 1 ]] && echo "Copied .desktop file to $AMDESKTOPDIR"
 	done
 	
@@ -116,11 +119,12 @@ amintegrate() {
     fi
 }
 
+# Delete / Uninstall AppImage.
 amdelete() {
     selectiondel=""
     if [[ -d "${APPIMAGEDIR}" ]] && [[ -d "${APPIMAGEICONDIR}" ]]; then
-        selectiondel="$(printf '%s\n' $(find "${APPIMAGEDIR}" -type f -iname "*.AppImage" | xargs -I {} basename {} | sort) | ${FMENU} "Choose an AppImage to remove: ")"
-        amname="$(basename -s AppImage ${selectiondel})"
+        selectiondel="$(printf '%s\n' "$(find "${APPIMAGEDIR}" -type f -iname "*.AppImage" | xargs -I {} basename {} | sort)" | ${FMENU} "Choose an AppImage to remove: ")"
+        amname="$(basename -s AppImage "${selectiondel}")"
 
         tput setaf 1 bold
         read -p "${selectiondel} will be uninstalled. Are you sure? [y/N] "
@@ -131,19 +135,19 @@ amdelete() {
                 rm "${APPIMAGEDIR}${selectiondel}" || echo "${selectiondel} was not found."
                 [[ "$verbose" -eq 1 ]] && echo "Deleted AppImage: ${selectiondel}"
 
-		founddesktop="$(grep -r "${selectiondel}" ${AMDESKTOPDIR} | awk -F ':' '{print $1}')"
+		founddesktop="$(grep -r "${selectiondel}" "${AMDESKTOPDIR}" | awk -F ':' '{print $1}')"
                 if [[ -n "$founddesktop" ]]; then
-		    [[ "$verbose" -eq 1 ]] && echo "Found .desktop files: $(printf '%s, ' ${founddesktop[@]})"
+		    [[ "$verbose" -eq 1 ]] && echo "Found .desktop files: $(printf '%s, ' "${founddesktop[@]}")"
 		    for desktopfile in ${founddesktop}
 		    do
-			[[ -f $desktopfile && -n $desktopfile ]] && rm $desktopfile
+			[[ -f $desktopfile && -n $desktopfile ]] && rm "$desktopfile"
 			[[ "$verbose" -eq 1 ]] && echo "Deleted AppImage .desktop file"
 		    done;
 		fi
-		foundicon="$(find ${APPIMAGEICONDIR} -type f -iname "${amname}*")"
-                if [[ -n $foundicon ]]; then
-                    rm $foundicon
-                    [[ "$verbose" -eq 1 ]] && echo "Deleted icon"
+		foundicon="$(find "$APPIMAGEICONDIR" -type f -iname "${amname}*")"
+                if [[ -n "$foundicon" ]]; then
+                    rm "${foundicon}"
+                    [[ "$verbose" -eq 1 ]] && echo "Deleted icon: ${foundicon}"
 		else
 		    echo "No icon was found."
 		fi
@@ -158,44 +162,47 @@ amdelete() {
     fi
 }
 
+# List installed AppImages.
 amlist() {
-    if [[ -n $(\ls ${APPIMAGEDIR}) ]]; then
+    if [[ -d "${APPIMAGEDIR}" ]]; then
 	echo "$(tput setaf 6 bold) AppImages currently installed:$(tput sgr0)"
-	tree ${APPIMAGEDIR} -P '*.AppImage' --prune --noreport | sed '1d'
+	tree "${APPIMAGEDIR}" -P '*.AppImage' --prune --noreport | sed '1d'
     else
 	echo "$(tput setaf 1 bold) No AppImages were found.$(tput sgr0)"
     fi
 }
 
+# Edit AppImage desktop entry (.desktop file).
 amedit() {
         if [[ ! -f $HOME/.cache/fzam-edit ]]; then
                 echo "By default fzam will open the .desktop file of an AppImage using the EDITOR variable."
                 echo "This is currently set to: ${EDITOR}"
                 echo "To override this run fzam like this: \$ EDITOR=PROGRAM fzam"
-                touch $HOME/.cache/fzam-edit
+                touch ~/.cache/fzam-edit
         fi
-        choice=$(grep -r -m 1 "\.AppImage" $AMDESKTOPDIR | sort | awk -F ":" '{print $1}' | ${FMENU} "Choose an AppImage entry to edit: ")
-        if [ -n $choice ]; then
-                $EDITOR $choice
+        choice=$(grep -r -m 1 "\.AppImage" "${AMDESKTOPDIR}" | sort | awk -F ":" '{print $1}' | ${FMENU} "Choose an AppImage entry to edit: ")
+        if [[ -n $choice ]]; then
+                $EDITOR "${choice}"
 	else
 	        exit 0
         fi
 }
 
+# Check for installed programs.
 _checks() {
-    if [ ! -d $APPIMAGEDIR ]; then
+    if [ ! -d "$APPIMAGEDIR" ]; then
 	echo "$APPIMAGEDIR directory does not exist. Creating it."
-	mkdir $APPIMAGEDIR
+	mkdir "$APPIMAGEDIR"
     fi
-    if [ ! -d $APPIMAGEICONDIR ]; then
+    if [ ! -d "$APPIMAGEICONDIR" ]; then
 	echo "$APPIMAGEICONDIR directory does not exist. Creating it."
-	mkdir $APPIMAGEICONDIR
+	mkdir "$APPIMAGEICONDIR"
     fi
-    if [ ! -d $AMDESKTOPDIR ]; then
+    if [ ! -d "$AMDESKTOPDIR" ]; then
 	echo "$AMDESKTOPDIR directory does not exist. Creating it."
-	mkdir $AMDESKTOPDIR
+	mkdir "$AMDESKTOPDIR"
     fi
-    if ! grep -q /home/john/Applications <<< $PATH; then
+    if ! grep -q /home/john/Applications <<< "$PATH"; then
 	echo "$HOME/Applications is not set in the PATH variable."
     fi
 
@@ -215,10 +222,7 @@ _checks() {
     fi
 }
 
-_version() {
-    echo "Fuzzy AppImage Manager v0.1"
-}
-
+# When called this function outputs the Help Text.
 _help() {
     cat <<EOF
 Description: Manage AppImages on Linux.
@@ -230,6 +234,7 @@ Usage: fzam [options]
 EOF
 }
 
+# This function executes whether the script runs with the -d flag or not.
 _maincmd() {
     tput setaf 3 bold
     echo "What would you like to do?"
@@ -243,24 +248,25 @@ _maincmd() {
     )
     choice=$(printf '%s\n' "${options[@]}" | ${FMENU} "")
     case $choice in
-	${options[0]})
+	"${options[0]}")
 		amintegrate
 		;;
-	${options[1]})
+	"${options[1]}")
 		amdelete
 		;;
-	${options[2]})
+	"${options[2]}")
 		amedit
 		;;
-	${options[3]})
+	"${options[3]}")
 		amlist
 		;;
-	${options[4]})
+	"${options[4]}")
 		echo "Program Terminated" && exit 0
 		;;
     esac
 }
 
+# Main Function.
 main() {
     _checks
     
@@ -280,7 +286,8 @@ main() {
 		_maincmd
 		;;
 	    -v | --version)
-		echo "FZAM | Fuzzy AppImage Manager v0.1"
+        echo "FZAM | Fuzzy AppImage Manager v0.1"
+        echo "Homepage: https://github.com/JRR-J/fzam"
 		;;
 	    *)
 		echo "Unknown argument: $1"
